# Generated by Django 4.2.5 on 2023-09-27 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="estado",
            field=models.CharField(default="usado", max_length=100),
        ),
    ]
