# Generated by Django 4.2.5 on 2023-09-24 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0002_purchased_items_seller_sold_items_usuario"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Usuario",
            new_name="User",
        ),
    ]
