# Generated by Django 4.2.5 on 2023-09-27 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0002_item_estado"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="estado",
            new_name="condition",
        ),
    ]
