# Generated by Django 4.2.5 on 2023-09-27 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0003_rename_estado_item_condition"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="created_date",
            field=models.DateField(),
        ),
    ]
