# Generated by Django 4.2.5 on 2023-10-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0005_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="", max_length=200),
        ),
        migrations.AddField(
            model_name="user",
            name="username",
            field=models.CharField(default="", max_length=200),
        ),
    ]
