# Generated by Django 4.2.5 on 2023-10-08 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0007_rename_user_user_mio"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Purchased_items",
        ),
        migrations.DeleteModel(
            name="Seller",
        ),
        migrations.DeleteModel(
            name="Sold_items",
        ),
        migrations.DeleteModel(
            name="User_mio",
        ),
    ]
