# Generated by Django 4.2.5 on 2023-10-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0008_delete_purchased_items_delete_seller_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="item",
            name="imagenItem",
            field=models.ImageField(blank=True, null=True, upload_to="imagenesitems"),
        ),
    ]
