# Generated by Django 4.2.5 on 2023-10-08 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0010_rename_imagenitem_item_image_item_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="appCoder.categ",
            ),
        ),
    ]
