# Generated by Django 4.2.5 on 2023-10-09 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0012_alter_item_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="categ",
            name="created_date",
        ),
        migrations.AlterField(
            model_name="item",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="imagenesitems"),
        ),
    ]
