# Generated by Django 4.2.5 on 2023-10-10 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("appCoder", "0013_remove_categ_created_date_alter_item_image"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Categoria",
        ),
        migrations.DeleteModel(
            name="Cocina",
        ),
        migrations.DeleteModel(
            name="Decoracion",
        ),
        migrations.DeleteModel(
            name="Muebles",
        ),
        migrations.DeleteModel(
            name="Tecnologia",
        ),
    ]
